import { useEffect, useState } from 'react';
import { invoicesApi } from '../../api/endpoints';
import { errorMessage, useToast } from '../../hooks/ToastContext';
import { MailIcon, SpinnerIcon } from './Icons';

const MUTED = { fontSize: 11.5, color: 'var(--muted)', marginTop: 6 };

/**
 * Dialog to email an invoice PDF to the customer.
 *
 * On open it asks the API for the recipient on file and the default subject and
 * message generated for this invoice, and shows them pre-filled. Both can be
 * edited before sending; "Reset to default" restores the generated text. The
 * company signature is appended by the server and shown read-only.
 */
export default function EmailInvoiceDialog({ invoice, onClose }) {
  const toast = useToast();
  const [to, setTo] = useState('');
  const [cc, setCc] = useState('');
  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  // Defaults as generated by the server; null when they could not be loaded.
  const [preview, setPreview] = useState(null);
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState(false);

  useEffect(() => {
    if (!invoice) return undefined;
    let alive = true;
    setLoading(true);
    setTo('');
    setCc('');
    setSubject('');
    setBody('');
    setPreview(null);

    invoicesApi.emailPreview(invoice.id)
      .then((res) => {
        if (!alive) return;
        const data = res.data || {};
        setPreview(data);
        setTo(data.to || '');
        setSubject(data.subject || '');
        setBody(data.body || '');
      })
      .catch(async () => {
        // Defaults unavailable (e.g. an older API): still allow sending with the
        // server's standard subject and message, and look the recipient up directly.
        try {
          const res = await invoicesApi.get(invoice.id);
          if (alive) setTo(res.data?.customer_email || '');
        } catch { /* recipient can be typed in */ }
      })
      .finally(() => { if (alive) setLoading(false); });

    return () => { alive = false; };
  }, [invoice]);

  useEffect(() => {
    if (!invoice) return undefined;
    const onKey = (e) => { if (e.key === 'Escape' && !sending) onClose(false); };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [invoice, sending, onClose]);

  if (!invoice) return null;

  const subjectLimit = preview?.limits?.subject || 200;
  const bodyLimit = preview?.limits?.body || 10000;
  const edited = Boolean(preview) && (subject !== (preview.subject || '') || body !== (preview.body || ''));

  const resetToDefault = () => {
    if (!preview) return;
    setSubject(preview.subject || '');
    setBody(preview.body || '');
  };

  const handleSend = async () => {
    const email = to.trim();
    if (!email) { toast.error('Enter at least one recipient email address'); return; }
    const payload = { email, cc: cc.trim() };
    if (preview) {
      if (!subject.trim()) { toast.error('Subject cannot be empty'); return; }
      if (!body.trim()) { toast.error('Message cannot be empty'); return; }
      payload.subject = subject.trim();
      payload.body = body;
    }
    setSending(true);
    try {
      const res = await invoicesApi.emailInvoice(invoice.id, payload);
      toast.success(res.data?.message || `Invoice emailed to ${email}`);
      onClose(true);
    } catch (err) {
      toast.error(errorMessage(err, 'Could not send the invoice email'));
    } finally {
      setSending(false);
    }
  };

  const busy = loading || sending;

  return (
    <div className="overlay" onClick={() => !sending && onClose(false)}>
      <div className="dialog" style={{ maxWidth: 640 }} onClick={(e) => e.stopPropagation()}>
        <span className="dialog-icon"><MailIcon width={20} height={20} /></span>
        <h3 style={{ fontSize: 18, marginBottom: 8 }}>Email invoice #{invoice.invoice_no}</h3>
        <p className="text-muted" style={{ margin: 0, fontSize: 13.5, lineHeight: 1.6 }}>
          The invoice PDF{preview?.attachment ? ` (${preview.attachment})` : ''} will be attached and sent to the
          customer{invoice.companyname ? ` (${invoice.companyname})` : ''}. Review the subject and message below and
          change them if needed.
        </p>

        {preview && preview.mailConfigured === false && (
          <div className="login-error" style={{ marginTop: 14 }}>
            Email sending is not configured on the server yet (SMTP_USER and SMTP_PASS), so this email cannot be sent.
          </div>
        )}

        <div className="form-field" style={{ marginTop: 16, textAlign: 'left' }}>
          <label htmlFor="emailTo">To</label>
          <input
            id="emailTo"
            type="text"
            value={to}
            onChange={(e) => setTo(e.target.value)}
            placeholder={loading ? 'Loading customer email…' : 'name@example.com, another@example.com'}
            disabled={busy}
            autoFocus
          />
          <div style={MUTED}>
            {!loading && !to
              ? 'No email on file for this customer — enter one to send.'
              : 'Separate multiple email addresses with commas.'}
          </div>
        </div>

        <div className="form-field" style={{ marginTop: 12, textAlign: 'left' }}>
          <label htmlFor="emailCc">CC <span style={{ color: 'var(--muted)', fontWeight: 400 }}>(optional)</span></label>
          <input
            id="emailCc"
            type="text"
            value={cc}
            onChange={(e) => setCc(e.target.value)}
            placeholder="cc1@example.com, cc2@example.com"
            disabled={busy}
          />
        </div>

        {(loading || preview) ? (
          <>
            <div className="form-field" style={{ marginTop: 12, textAlign: 'left' }}>
              <label htmlFor="emailSubject">Subject</label>
              <input
                id="emailSubject"
                type="text"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                placeholder={loading ? 'Loading default subject…' : 'Email subject'}
                maxLength={subjectLimit}
                disabled={busy}
              />
            </div>

            <div className="form-field" style={{ marginTop: 12, textAlign: 'left' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: 12 }}>
                <label htmlFor="emailBody">Message</label>
                {edited && (
                  <button
                    type="button"
                    onClick={resetToDefault}
                    disabled={busy}
                    style={{ background: 'none', border: 'none', padding: 0, cursor: 'pointer', color: 'var(--purple-600)', fontSize: 12.5, fontWeight: 600, fontFamily: 'inherit' }}
                  >
                    Reset to default
                  </button>
                )}
              </div>
              <textarea
                id="emailBody"
                rows={12}
                value={body}
                onChange={(e) => setBody(e.target.value)}
                placeholder={loading ? 'Loading default message…' : 'Email message'}
                maxLength={bodyLimit}
                disabled={busy}
                style={{ resize: 'vertical', lineHeight: 1.55, minHeight: 180 }}
              />
              <div style={MUTED}>
                {edited ? 'Edited for this email only. ' : 'Default message for this invoice. '}
                Leave a blank line between paragraphs. A paragraph wrapped in **double asterisks** is highlighted in red.
              </div>
            </div>

            {preview?.signature && (
              <div className="form-field" style={{ marginTop: 12, textAlign: 'left' }}>
                <label>Signature <span style={{ color: 'var(--muted)', fontWeight: 400 }}>(added automatically)</span></label>
                <pre style={{
                  margin: 0, padding: '10px 12px', background: 'var(--line-soft)', border: '1px solid var(--line)',
                  borderRadius: 'var(--r-md)', fontFamily: 'inherit', fontSize: 12.5, lineHeight: 1.55,
                  color: 'var(--muted)', whiteSpace: 'pre-wrap', wordBreak: 'break-word',
                }}
                >
                  {preview.signature}
                </pre>
              </div>
            )}
          </>
        ) : (
          <div style={{ ...MUTED, marginTop: 14, fontSize: 12.5 }}>
            The standard subject and message will be used for this email.
          </div>
        )}

        <div className="form-actions">
          <button className="btn btn-primary" onClick={handleSend} disabled={busy}>
            {sending ? <><SpinnerIcon width={15} height={15} /> Sending…</> : <><MailIcon width={15} height={15} /> Send invoice</>}
          </button>
          <button className="btn btn-secondary" onClick={() => onClose(false)} disabled={sending}>Cancel</button>
        </div>
      </div>
    </div>
  );
}
